### ISSUE TITLE
Create image for domain model from mermaid graph and add to README

### ISSUE THREAD

**Issue by glgoose** [datopian/quizzical#1]
## Acceptance Criteria

* [ ] the domain model graph is visible in the README

## Tasks

* [ ] convert mermaid graph to image
* [ ] add image to README

## Analysis

GitHub weirdly does not support mermaid
You can see the feature request here (weirdly they also don't use an issue tracker for features): https://github.community/t5/How-to-use-Git-and-GitHub/Feature-Request-Support-Mermaid-markdown-graph-diagrams-in-md/td-p/21967
